<?php echo $this->doctype(); ?>

<html lang="de">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Betmanagement'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                    <img src="<?php echo $this->basePath('img/logo32.png') ?>" alt="Betmanagement"/>&nbsp; 
                    <?php echo $this->translate('Betmanagement') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    
                        <ul class="nav navbar-nav">
                        <?php /* ?><li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li> */ ?>
                        <li class=""><a href="/client/login"><?php echo $this->translate('login') ?></a></li>
                        <li class=""><a href="/client/index"><?php echo $this->translate('index') ?></a></li>
                        <li class=""><a href="/client/register"><?php echo $this->translate('register') ?></a></li>
                        <li class=""><a href="/client/test1"><?php echo $this->translate('test1') ?></a></li>
                        <li class=""><a href="/client/logout"><?php echo $this->translate('logout') ?></a></li>
                        <li class=""><a href="/services"><?php echo $this->translate('services') ?></a></li>
                        <li class=""><a href="/services/wsdl"><?php echo $this->translate('wsdl') ?></a></li>

                    </ul>
                </div><!--/.nav-collapse -->

<?php /*
<div>
<?php // <-- Update this !!
echo $this->navigation('navigation')
    ->menu()
    ->setMinDepth(0)
    ->setMaxDepth(3)
    ->setUlClass('nav')
    ->render();
?>
</div>
*/?>
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2014 - <?php echo date('Y') ?> by JF & SS <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
