<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Client\Module'                        => __DIR__ . '/Module.php',
    'Client\Controller\StartController' => __DIR__ . '/src/Client/Controller/StartController.php',
    'ClientTest\Framework\TestCase'        => __DIR__ . '/tests/Client/Framework/TestCase.php',
    'ClientTest\SampleTest'                => __DIR__ . '/tests/Client/SampleTest.php',
);
